language: python
python:
  - "3.6-dev" 
 
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE ahmad;" -U postgres

install: 
  - pip install -r requirements.txt


script:
  - pytest -v --cov app --cov-report term-missing
  - coverage report

after_success:
- coveralls
  
