language: python
python:
  - "3.6-dev" 
  - 3.5
  - 3.4
 

install:
  - pip install -r requirements.txt

script:
  - pytest --cov --coverage-test_order
  - coverage


after_succes:
  - coveralls 

  
